---
# tasks file for save-template
- name: Authorize with {{ engine_fqdn }}
  ovirt_auth:
    url: "https://{{ engine_fqdn }}/ovirt-engine/api"
    username: "{{ engine_user }}"
    password: "{{ engine_password }}"

- name: Get VM info
  ovirt_vm_info:
    auth: "{{ ovirt_auth }}"
    pattern: "{{ source_vm }}"
  register: found_vms

- name: Shutdown, Unprotect, and Remove {{ source_vm }} if there
  block:
    - name: Shutdown the machine to be deleted
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ source_vm }}"
        cluster: "{{ rhvm_cluster }}"
        state: stopped

    - name: Remove Delete Protection if Requested
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ source_vm }}"
        delete_protected: False
      when: force_delete

    # tasks file for roles/remove-vm
    - name: Remove the target vm, {{ source_vm }}
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ source_vm }}"
        state: absent
  when: found_vms["ovirt_vms"]| length > 0

- name: Logout from {{ engine_fqdn }}
  ovirt_auth:
    ovirt_auth: "{{ ovirt_auth }}"
    state: absent

# If the {{ source_vm }} named passed to the role DNE, let's
# return a failure so it is obvious something went wrong instead
# of the role passing without issue.
- name: Fail the play as no vm was passed to the role
  fail:
    msg: "No VMs was passed to the role, or the VM passed not found"
  when: found_vms["ovirt_vms"]| length == 0
