---
# defaults file for deploy-base-sla
# Defines the vars required for deploying a template
#vm_definition: 'deploy-template-config.yml'
vm_definition: ''
# Attempt to wait for VM dictionary of IP information
wait_for_ip: true
vm_infra_wait_for_ip_retries: 20
vm_infra_wait_for_ip_delay: 10

# Default RHVM template to deploy
template: rhel-7.7-latest
#template: satellite-6.7-latest
debug_vm_create: true

# RHVM where VMs are deployed
engine_fqdn: ""

# Template Variables
custom_name: ""
rhvm_hostname: "{{ ansible_user_id }}-{{ template }}-{{ ansible_date_time.epoch }}{{ custom_name }}"
sat_username: admin
sat_password: changeme

# Default public ssh key to use
user_ssh_key: "~/.ssh/id_rsa.pub"

# Required wait for FQDN resolution or playbook errors on dictionary return
timeout: 30

# Required: dictionary that defines "vms:"
# For more customizable options in deploying a VM, see:
# external-roles/ovirt.vm-infra/README.md
deploy_template:
  cluster: Default
  template: "{{ template }}"
  memory: 20GiB
  cores: 2
  state: running
  cloud_init:
    authorized_ssh_keys: "{{ jenkins_public_ssh_key }}\n{{ lookup('file', '{{ user_ssh_key }}') }}"
  cloud_init_persist: true

# Dictionary that defines the deployed VM
# Note: Playbook can currently only handle a single VM deployment
# ToDo: Improve the deployment to several VMs, if commonly needed by end-users
vms:
  - name: "{{ rhvm_hostname }}"
    tag: deploy_template
    profile: "{{ deploy_template }}"

#SLA variables
# Number of time units to wait befroe the VM is shutdown and is waiting for a cleanup
sla_expire: 3

# Length of the time unit in seconds. The default is 86400 - one day. This way we can change expire time easily, and use
# days, hours, weeks, years...whatever.
sla_expire_unit: 86400
