---
- name: Run mac-pools sub-role
  import_role:
    name: "ovirt.infra/roles/ovirt.mac-pools"

- name: Run datacenters sub-role
  import_role:
    name: "ovirt.infra/roles/ovirt.datacenters"

- name: Run clusters sub-role
  import_role:
    name: "ovirt.infra/roles/ovirt.clusters"

- name: Run hosts sub-role
  import_role:
    name: "ovirt.infra/roles/ovirt.hosts"

- name: Run networks sub-role
  import_role:
    name: "ovirt.infra/roles/ovirt.networks"

- name: Run storages sub-role
  import_role:
    name: "ovirt.infra/roles/ovirt.storages"

- name: Run aaa-jdbc sub-role
  import_role:
    name: "ovirt.infra/roles/ovirt.aaa-jdbc"
  when: users is defined or user_groups is defined

- name: Run external-providers sub-role
  import_role:
    name: "ovirt.infra/roles/ovirt.external-providers"

- name: Run permissions sub-role
  import_role:
    name: "ovirt.infra/roles/ovirt.permissions"
