---
- name: Check if mandatory variables are set
  fail:
    msg: "Either ovirt_repositories_pool_ids or ovirt_repositories_pools must be defined."
  when:
    - "ovirt_repositories_pool_ids is not defined"
    - "ovirt_repositories_pools is not defined or ovirt_repositories_pools | list | length == 0"

- name: Check if mandatory variables are set
  fail:
    msg: "Both ovirt_repositories_pool_ids and ovirt_repositories_pools can't be defined, only one of them."
  when:
    - "ovirt_repositories_pool_ids is defined"
    - "ovirt_repositories_pools is defined"

- name: Ensure subscription-manager package is installed
  package:
    name: subscription-manager
    state: present

- name: Register and subscribe to multiple pool IDs
  redhat_subscription:
    state: present
    force_register: "{{ ovirt_repositories_force_register }}"
    username: "{{ ovirt_repositories_rh_username | mandatory }}"
    password: "{{ ovirt_repositories_rh_password | mandatory }}"
    pool_ids: "{{ ovirt_repositories_pool_ids }}"
    server_hostname: "{{ ovirt_repositories_rhsm_server_hostname | default(omit) }}"
  when: ovirt_repositories_pool_ids is defined

- name: Register to and subscribe to pool
  redhat_subscription:
    state: present
    force_register: "{{ ovirt_repositories_force_register }}"
    username: "{{ ovirt_repositories_rh_username | mandatory }}"
    password: "{{ ovirt_repositories_rh_password | mandatory }}"
    pool: "^({{ ovirt_repositories_pools | list | map('regex_escape') | join(')$|^(') }})$"
    server_hostname: "{{ ovirt_repositories_rhsm_server_hostname | default(omit) }}"
  when: ovirt_repositories_pools is defined

- name: Include target/version specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ovirt_repositories_target_host }}_{{ ovirt_repositories_ovirt_version }}.yml"
    - "default.yml"
  when: ovirt_repositories_subscription_manager_repos is not defined

- name: Enable required repositories
  rhsm_repository:
    name: "{{ item }}"
    state: "enabled"
  with_items: "{{ ovirt_repositories_subscription_manager_repos | default([]) }}"
