---
tower_inventory_sources:
  - name: RHVM-01
    source: rhv
    inventory: RHVM-01
    credential: admin@internal-RHVM-01
    description: created by Ansible Tower
    overwrite: True
    update_on_launch: True
    update_cache_timeout: 0

  - name: RHVM-02
    source: rhv
    inventory: RHVM-02
    credential: admin@internal-RHVM-02
    description: created by Ansible Tower
    overwrite: True
    update_on_launch: True
    update_cache_timeout: 0

    # more options can be provided but for RHV source we are using, we need only this much.
  - name: project-inventory-source-satlab-tower
    inventory: satlab-tower-inventory
    source: scm
    source_project: satlab-tower-master
    source_path: inventory/hosts
    overwrite: True
    overwrite_vars: True
    update_on_launch: True
    update_cache_timeout: 1800

  - name: satlab-tower-tower-inventory-rhvm-02
    custom_virtualenv: /opt/virtualenvs/satlab-venv/
    source: scm
    source_path: inventory/hosts
    source_project: satlab-tower-master
    inventory: RHVM-02
    description: created by Ansible Tower
    overwrite: True
    overwrite_vars: True
    update_on_launch: True
    update_cache_timeout: 1800

  - name: satlab-tower-master-inventory-rhvm-01
    custom_virtualenv: /opt/virtualenvs/satlab-venv/
    source: scm
    source_path: inventory/hosts
    source_project: satlab-tower-master
    inventory: RHVM-01
    description: created by Ansible Tower
    overwrite: True
    overwrite_vars: True
    update_on_launch: True
    update_cache_timeout: 1800
