---
tower_inventories:
  - name: localhost
    description: inventory for localhost
    organization: Satellite
    variables: {'ansible_connection': 'local'}
  - name: satlab-tower-inventory
    description: Load inventory from satlab-tower hosts file
    organization: Satellite
  - name: RHVM-01
    organization: Satellite
    description: created by Ansible Playbook - for RHVM-01
    state: present
  - name: RHVM-02
    organization: Satellite
    description: created by Ansible Playbook - for RHVM-02
    state: present
  - name: My Inventory - kkulkarni
    organization: Satellite
    description: Smart inventory containing all VMs you own
    state: present
    kind: smart
    host_filter: "name__icontains=kkulkarni"
  - name: My Inventory - bherring
    organization: Satellite
    description: Smart inventory containing all VMs you own
    state: present
    kind: smart
    host_filter: "name__icontains=bherring"
  - name: My Inventory - rdrazny
    organization: Satellite
    description: Smart inventory containing all VMs you own
    state: present
    kind: smart
    host_filter: "name__icontains=rdrazny"
  - name: My Inventory - ltran
    organization: Satellite
    description: Smart inventory containing all VMs you own
    state: present
    kind: smart
    host_filter: "name__icontains=ltran"
  - name: My Inventory - jcalla
    organization: Satellite
    description: Smart inventory containing all VMs you own
    state: present
    kind: smart
    host_filter: "name__icontains=jcalla"
  - name: Infra Inventory
    organization: Satellite
    description: Smart inventory containing all Infra VMs
    state: present
    kind: smart
    host_filter: "name__icontains=infra"
  - name: Env Inventory
    organization: Satellite
    description: Smart inventory containing all Env VMs
    state: present
    kind: smart
    host_filter: "name__icontains=env"
