---
tower_setting_params:
  - key: TOWER_URL_BASE
    value: "https://{{  ovirt_tag_deploy_template | default(target_hosts or 'localhost') }}"
  - key: AWX_TASK_ENV
    value: {'GIT_SSL_NO_VERIFY': 'True'}
  - key: AUTH_LDAP_SERVER_URI
    value: "ldap://ldap.corp.redhat.com"
  - key: AUTH_LDAP_USER_DN_TEMPLATE
    value: "uid=%(user)s,ou=Users,dc=redhat,dc=com"
  - key: AUTH_LDAP_GROUP_SEARCH
    value: "['dc=redhat,dc=com', 'SCOPE_SUBTREE', '(objectClass=person)']"
  - key: AUTH_LDAP_GROUP_TYPE
    value: "GroupOfUniqueNamesType"
  - key: AUTH_LDAP_USER_SEARCH
    value: "['OU=Users,DC=redhat,DC=com', 'SCOPE_SUBTREE', '(cn=%(user)s)']"
  - key: AUTH_LDAP_START_TLS
    value: true
  - key: AUTH_LDAP_GROUP_TYPE_PARAMS
    value: {}
  - key: AUTH_LDAP_REQUIRE_GROUP
    value: "cn=satellite-qe,ou=adhoc,ou=managedGroups,dc=redhat,dc=com"
  # Next key helps fetch Email addr and name from LDAP and save it in tower user.
  - key: AUTH_LDAP_USER_ATTR_MAP
    value: '{"first_name": "displayName","last_name": "sn","email": "rhatPrimaryMail"}'
  # Next key helps each sat-qe-infra group to become superuser in tower as soon as they login
  - key: AUTH_LDAP_USER_FLAGS_BY_GROUP
    value: "{u'is_superuser': ['cn=sat-qe-infra,ou=adhoc,ou=managedGroups,dc=redhat,dc=com']}"
  - key: CUSTOM_VENV_PATHS
    value:
      - "{{ satlab_venv_location }}"
  # This maps all users to satellite-qe org and makes sure they are not part of satlab-admin
  - key: AUTH_LDAP_ORGANIZATION_MAP
    value: '{
     "Satellite": {
      "users": true
     }
    }'
  # This maps all users to satellite-qe team and we need to add this team to all resources we create for them
  # that way users can access the things that their team has permissions for
  - key: AUTH_LDAP_TEAM_MAP
    value: '{
     "satellite-qe": {
      "organization": "Satellite",
      "users": true
     },
     "satlab-admin": {
      "organization": "Satellite",
      "users": "cn=sat-qe-infra,ou=adhoc,ou=managedGroups,dc=redhat,dc=com"
     }
    }'
