---
tower_credentials:
  - kind: rhv
    name: admin@internal-RHVM-01
    description: infra-rhvm-01 creds for inventory sources.
    host: "https://{{ rhvm_01_fqdn }}/ovirt-engine/api"
    username: "{{ rhvm_01_user }}"
    password: "{{ rhvm_01_password }}"
    organization: Satellite
  - kind: rhv
    name: admin@internal-RHVM-02
    description: infra-rhvm-02 creds for inventory sources.
    host: "https://{{ rhvm_02_fqdn }}/ovirt-engine/api"
    username: "{{ rhvm_02_user }}"
    password: "{{ rhvm_02_password }}"
    organization: Satellite
  - kind: ssh
    organization: Satellite
    name: machine-creds-with-jenkins-pvt-key
    description: This credential can be used with any vm that contains jenkins_public key in authorized keys
    username: root
    ssh_key_data: "{{ jenkins_private_ssh_key }}"
  - kind: scm
    name: gitlab-personal-access-token for satqe_auto_droid
    description: General purpose token that can be used by anyone for satlab-tower (or other private) repo clone
    username: gitlab
    password: "{{ gitlab_automation_user_personal_access_token }}"
    organization: Satellite
  - kind: vault
    name: satlab-tower-vault
    vault_password: "{{ vault_admin_secret }}"
    vault_id: admin
    description: satlab-tower-vault password aka vault_admin_secret
    organization: Satellite
  - kind: vault
    name: satlab-user-vault
    vault_password: "{{ vault_user_secret }}"
    vault_id: user
    description: satlab-users-vault password aka vault_user_secret
    organization: Satellite
