---
tower_notifications:
  - name: irc-satqe-chat-notification
    description: Notify us on job in IRC!
    organization: Satellite
    notification_type: irc
    nickname: Ansible-Tower-Stage-Bot-01
    port: 6667
    server: irc.devel.redhat.com
    targets:
      - '#satqe-infra'
      - 'kkulkarni'
    password: ''  # this is required even if there's no password
  - name: Email notification
    description: Send out emails for tower jobs
    organization: Satellite
    notification_type: email
    host: smtp.redhat.com
    recipients:
      - satlab-admins@redhat.com
      - kkulkarni@redhat.com
    sender: satlab-admins@redhat.com
    port: 25
    username: '' # this is required even if there's no username
    password: '' # this is required even if there's no password
    state: present
  - name: bherring Email job notification
    description: Send out Dev job notification
    organization: Satellite
    notification_type: email
    host: smtp.redhat.com
    recipients:
      - bherring@redhat.com
    sender: satlab-admins@redhat.com
    port: 25
    username: '' # this is required even if there's no username
    password: '' # this is required even if there's no password
    state: present
