---
# tasks to uninstall nonuser IPA client

- name: Uninstall - Uninstall nonuser IPA client
  command: >
    /usr/sbin/ipa-client-install
    --uninstall
    -U
  register: uninstall
  # 2 means that uninstall failed because IPA client was not configured
  failed_when: uninstall.rc != 0 and uninstall.rc != 2
  changed_when: uninstall.rc == 0

- name: uninstall packages
  command: yum remove -y rhit-idm-configs
