# Purpose:
# Install Satellite on a dynamically deployed template
---
- name: Deploying a Template on RHVM
  hosts: localhost
  gather_facts: true
  vars:
    # Defines the vars required for deploying a template
    - vm_definition: 'deploy-template-config.yml'
    # Attempt to wait for VM dictionary of IP information
    - wait_for_ip: true
    - vm_infra_wait_for_ip_retries: 20
    - vm_infra_wait_for_ip_delay: 10

  vars_files:
  - "{{ vm_definition }}"

  # Deploys the template
  roles:
    - external-roles/ovirt.vm-infra

  # Reaps information from the VM
  post_tasks:

  - name: Post-task for newly created VMs
    import_tasks: ../vm-deploy-helpers/post-vm-create-tasks.yml

- name: Import the initialize-template playbooks after deploy
  import_playbook: ../vm-deploy-helpers/initialize-template.yml

- name: Install Satellite
  hosts: ovirt_tag_deploy_template
  vars:
    # Defines the vars required for deploying a template
    - initialize_definition: 'deploy-template-config.yml'
    - new_hostname: "{{ hostvars['localhost']['ovirt_vms'][0]['fqdn'] }}"
  vars_files:
  - "{{ initialize_definition }}"

  roles:
    - infra-install/subscription-manager
    - infra-install/install-satellite
    - infra-install/fake_manifests
    # MR next: - infra-install/update-template

  post_tasks:

    - name: Output the RHVM VM name with the VM FQDN name
      debug:
        msg:
        - "Host has been provisioned: {{ rhvm_hostname }} with FQDN {{ new_hostname }}"
