- name: Add tower org
  awx.awx.tower_organization:
     name:                   "{{ item.name }}"
     custom_virtualenv:      "{{ item.custom_virtualenv | default(omit) }}"
     state:                  "{{ item.state| default('present') }}"
     tower_host:             "{{ tower_hostname }}"
     tower_username:         "{{ tower_username | default('admin') }}"
     tower_password:         "{{ tower_admin_password }}"
     tower_verify_ssl:       "{{ tower_verify_ssl | default('false')}}"
  loop: "{{ tower_organization }}"
  tags:
    - tower-org-create
