---
- name: Run objects backup to generate json file
  awx.awx.tower_receive:
    all: yes
    tower_host:       "{{ tower_hostname }}"
    tower_username:   "{{ tower_username | default('admin') }}"
    tower_password:   "{{tower_admin_password}}"
    tower_verify_ssl: "{{ tower_verify_ssl | default('false')}}"
  register: json_backup_data

- name: Copy content from backup data to a file
  copy:
    content: "{{ json_backup_data }}"
    dest: "{{ backup_json_file }}"

- name: Symlink "{{ backup_json_file }}" to backup-latest.json
  file:
    src: "{{ backup_json_file }}"
    dest: "{{ backup_path }}/backup-latest.json"
    state: link
