---
# Note: This playbook needs ansible-tower-cli installed and configured to run successfully.
- name: Playbook to configure ansible tower for ldap authentication
  hosts: "{{ target_hosts | default('ovirt_tag_deploy_template') }}"
  pre_tasks:
    - name: Include vars from tower-configs directory
      include_vars:
        dir: tower-configs
        ignore_files: [tower-config.yml.template]
        extensions: ["json", "yaml", "yml"]
  roles:
    - { role: roles/tower-roles/tower-cli-installer}
    - { role: roles/tower-roles/tower-settings, when: tower_setting_params is defined}

  tasks:
    # Add Red Hat CA Cert and update ca trust so that LDAP config works
    - name: Copy Red Hat CA Cert to correct location
      get_url:
        url: https://password.corp.redhat.com/RH-IT-Root-CA.crt
        dest: /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt
        mode: '0644'

    - name: Update CA Trust
      command: update-ca-trust
