# Purpose:
# - Deploy VM from templates on RHVM-01 and install Ansible Tower on it
# - Usage template derived from:
#     - https://github.com/oVirt/ovirt-ansible-vm-infra/blob/master/README.md
# - Deployment is done on localhost as the role and module use the RHVM API
# - Please see the Confluence for more details about venv setup
#     - https://docs.engineering.redhat.com/display/SQE/HowTo+Deploy+a+Template+in+Satlab
---
- name: Deploying a Template on "{{ engine_fqdn }}"
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    # Defines the vars required for deploying a template
    - vm_definition: 'deploy-template-config.yml'
    # Attempt to wait for VM dictionary of IP information
    - wait_for_ip: true
    - vm_infra_wait_for_ip_retries: 20
    - vm_infra_wait_for_ip_delay: 10

  vars_files:
    - "{{ vm_definition }}"

  # Deploys the template
  roles:
    - role: external-roles/ovirt.vm-infra

  # Reaps information from the VM
  post_tasks:
    - name: Import set of post tasks for newly created VM
      import_tasks: ../vm-deploy-helpers/post-vm-create-tasks.yml

- import_playbook: ../vm-deploy-helpers/initialize-template.yml


- name: Install tower
  hosts: ovirt_tag_deploy_template
  vars:
    # Defines the vars required for deploying a template
    - vm_definition: 'deploy-template-config.yml'
  vars_files:
    - "{{ vm_definition }}"
  roles:
    - role: infra-install/subscription-manager
      when: ansible_distribution == 'RedHat'
    - role: add-storage-network
      when: nmcli_ethernet is defined
    - role: ome.nfs_mount
      nfs_share_mounts:
        - path: "{{ backup_path }}"
          location: "{{ nfs_server_backup_vol }}"
      when: backup_path is defined and nfs_server_backup_vol is defined
    - role: roles/tower-roles/deploy_ansible_tower
    - role: roles/tower-roles/tower-cli-installer
  post_tasks:
    - name: Output Hostname
      debug:
        msg:
        - "The tower vm {{inventory_hostname}} is now ready."
        - "The FQDN is {{ hostvars['localhost']['ovirt_vms'][0]['fqdn'] }}"
