---
- name: Backup Ansible Tower - JSON backup - only metadata/objects
  hosts: "{{ target_hosts }}"

  pre_tasks:
    - name: Include vars for tower hostname, user,password
      include_vars: tower-configs/tower-hostname.yml
  roles:
    - role: roles/tower-roles/tower-backup
      meta_backup: True
      backup_path:  /mnt/backups
