---
- name: Playbook to allow you to upgrade existing ansible tower
  hosts: "{{ target_hosts }}"
  roles:
    - role: infra-install/subscription-manager
      when: ansible_distribution == 'RedHat'
    - role: deploy_ansible_tower
      tower_setup_bundle_tar_url: https://releases.ansible.com/ansible-tower/setup-bundle/ansible-tower-setup-bundle-latest.el7.tar.gz
